//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiveReader2.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LiveReader2.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (function () {
        ///    // Functions
        ///    function SelectedSport() {
        ///        let divSport = document.querySelector(&quot;a.menuTop__item--active &gt; div.menuTop__text&quot;) || document.querySelector(&quot;a.menuMinority__item--active &gt; div.menuMinority__text&quot;);
        ///        return divSport.textContent.trim();
        ///    }
        ///    function SelectedDay() {
        ///        let shortDay = document.querySelector(&quot;.calendar__datepicker&quot;).textContent.split(&apos; &apos;)[0];
        ///        let s = shortDay.split(&apos;/&apos;);
        ///        let day = s[0];
        ///        let month = s[1] [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FlashScoreFootball {
            get {
                return ResourceManager.GetString("FlashScoreFootball", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (function () {
        ///    let data = {};
        ///    let table_live = document.querySelector(&quot;#f24com_tablelive&quot;);
        ///    let table_results = document.querySelector(&quot;#f24com_tableresults&quot;);
        ///    // Selected Date
        ///    let s = document.querySelector(&quot;#f24com_date &gt; span&quot;).textContent.split(&quot;.&quot;);
        ///    let day = parseInt(s[0]);
        ///    let month = parseInt(s[1]) - 1;
        ///    let year = parseInt(s[2]);
        ///    let today_date = new Date(year, month, day);
        ///    let tomorrow_date = new Date(year, month, day + 1);
        ///    let today = today_da [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Futbol24 {
            get {
                return ResourceManager.GetString("Futbol24", resourceCulture);
            }
        }
    }
}
